service: sls-aws-spring-cloud-function
provider:
  name: aws
  runtime: java17
  timeout: 10
package:
  artifact: target/aws-java-spring-cloud-function-demo-0.0.1-SNAPSHOT-aws.jar
functions:
  members:
    handler: com.controller.S3_Transcribe.handleRequest
    environment:
      FUNCTION_NAME: members